### ISSUE TITLE
(might be user err)

### ISSUE THREAD

**Issue by 182exe** [sammwyy/BLEeding#1]
` Thread pool throws an exception: argument 2 (impossible<bad format char>) `

using command ` python bleeding deauth 84:AB:1A:3A:**:** -P rfcomm `

do you know if i can solve this somehow?

**Comment by sammwyy** [comment]
Apparently it is a bug in the Bluetooth library which does not support python >= 3.12.

BLEding works perfectly on my Raspberry PI which uses Python 3.11.2. You can try to downgrade.

**Comment by 182exe** [comment]
alright, ill get back to u
